### ISSUE TITLE
Group Policy PowerShell Transcript Logs/Just Enough Administration

### ISSUE THREAD

**Issue by jhack31** [PowerShell/JEA#12]
I have a group policy deployed to enable PowerShell transcript logging, which works.  However, when I deploy JEAEndpoints with DSC, I get an error message when trying to launch the JEASession - "Cannot write to a Closed TextWriter"  Has anyone else seen this issue?

**Comment by rpsqrd** [comment]
Hey @jhack31,

Are you using PowerShell 5.0? We have seen this a few times with PS 5.0 and included a fix in PS 5.1. You can grab the download files and installation instructions here: https://msdn.microsoft.com/en-us/powershell/wmf/5.1/install-configure

Ryan

**Comment by jhack31** [comment]
I opened a ticket on this and they suggested upgrading to WMF 5.1.  I can confirm the issue did not persist in 5.1.

Thanks!
