### ISSUE TITLE
Quick way to reset dsclocalconfigurationmanager to default

### ISSUE THREAD

**Issue by jhack31** [PowerShell/JEA#13]
Working in a test environment and have played around with setting pull mode on the local configuration manager.  Is there a quick way to set the settings back to the defaults?

**Comment by rpsqrd** [comment]
@jhack31 I believe the quickest way would be to just create a new meta config file that simply doesn't use any pull servers in it. There's no built-in "revert to default" cmdlet. Closest thing is to just replace the meta config with one that points to no external servers, and run `Remove-DscConfigurationDocument` for any other DSC config files applied to the system.

**Comment by rpsqrd** [comment]
Closing as this issue is now 2 months old. If you have further questions about DSC, open an issue on [DscResources](https://github.com/PowerShell/DscResources).

**Comment by jnury** [comment]
For reference, I wrote this doc: https://jnury.github.io/DSC_reset_lcm_configuration
