### ISSUE TITLE
VisibleCmdlets?

### ISSUE THREAD

**Issue by jhack31** [PowerShell/JEA#14]
Is it possible to pass a variable into the VisibleCmdlets section of a Role Capability? Example below:

$approved=@('service1','service2')

VisibleCmdlets = @{Name = 'Get-Service; Parameters=@{Name='Name'; ValidateSet = $approved} } 

When I attempt to do that I get an error: "Enter-PSSession : Processing data from remote server localhost failed with the following error message: A null key is not allowed in a hash literal. For more information, see the about_Remote_Troubleshooting Help topic."

**Comment by rpsqrd** [comment]
@jhack31 You can pass variables into the `New-PSRoleCapability` cmdlet, but the resulting data file (.psrc) must not contain variables. The .psrc file is simply a data file (similar to JSON), and should contain explicit, static lists of allowable commands and resources.

**Comment by rpsqrd** [comment]
Closing as this issue is now 2 months old. Please feel free to re-open if you have further questions.
