### ISSUE TITLE
Support for Private PS Gallery Repo as Source

### ISSUE THREAD

**Issue by matthitchcock** [PowerShell/JEA#19]
Is there a plan to add support for downloading from a Private PS Gallery repo? I notice there is a PowerShellGet cmdlet for Get-RoleCapability, will this be incorporated in some way?

**Comment by rpsqrd** [comment]
Hi Matt,

There isn't any support planned at the moment, but if it's something you'd like to see I'd encourage you to submit an issue on the [PowerShellGet repo](https://github.com/PowerShell/PowerShellGet/issues). I would like to point out that these are simply convenience commands, however, and any module you install from any source will bring any role capabilities along with it. These commands just make it easier to search for modules with them.

Ryan
