### ISSUE TITLE
NativeCommandError

### ISSUE THREAD

**Issue by jhack31** [PowerShell/JEA#24]
I have a use case where we would like to apply a JEA configuration that allows an external program which is in the form of a command-line utility.  I have exposed the command in the  Visible External Commands section, but when I try to run the command from the configuration, I get an error:

.\<command-line tool> -- <Tool title>
    + CategoryInfo          : NotSpecified: (<command-line tool>s:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Is there a workaround for this behavior?

Thanks!

**Comment by rpsqrd** [comment]
@PaulHigin Do you know what can cause that Error ID?

**Comment by PaulHigin** [comment]
I would need repro steps to investigate.  Have you tried running the command line tool in a normal remote session?  Do you get the error only on a JEA endpoint?

**Comment by jhack31** [comment]
I found a thread regarding this issue: https://stackoverflow.com/questions/10666101/lastexitcode-0-but-false-in-powershell-redirecting-stderr-to-stdout-gives-n

This does in fact reproduce my error (exposing cmd.exe AS a VisibleExternalCommand - Note: I'm not using cmd.exe in that variable, this is just a sample to repro):
1. Enter-PSSession -ComputerName <server>
2. cmd /c "echo Hello from standard error 1>&2"

I get the error: 
```
[<server>]: PS C:\Users\<user>\Documents> cmd /c "echo Hello from standard error 1>&2"
cmd : Hello from standard error
    + CategoryInfo          : NotSpecified: (Hello from standard error :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

This fails in a normal remote session also.  So it looks like the command line program I'm trying to allow writes to standard error and it's causing an issue when remoting with PowerShell.  I hope that helps to understand and hopefully there is a workaround.

Thanks!
Justin

**Comment by PaulHigin** [comment]
Yeah, PowerShell remoting converts native error stream messages into PowerShell ErrorRecord objects.  This seems inconsistent with PowerShell a local PowerShell session.  Some people feel one way is correct and the other not correct.  There is an issue discussing this (mostly for PowerShell local session) on the PowerShell GitHub site.  (https://github.com/PowerShell/PowerShell/issues/4002)
