### ISSUE TITLE
Missing psrc file get's non descriptive error on connection

### ISSUE THREAD

**Issue by artisticcheese** [PowerShell/JEA#3]
Hello,

I need my modules to be loaded off UNC share and they are setup to do that via ModulesToImport entry in PSSC file. RoleCapabilities folder is there along with PSRC file but that one is not being checked since PSModulePath is no specifying that folder and hence connectiong fails. ON front-end it's showing very non-descriptive error. On the box itself it's very descriptive via Get-PSssessionCapability execution. Is it possible to modify PSModulePath specificially for specific session? I don't want to do it on machinelevel since specifying UNC path on machine level will break if machine does not have access to UNC path.

> PS C:\windows\system32> Enter-PSSession server1 -ConfigurationName Jea -Credential $testcred 
> Enter-PSSession : Processing data from remote server server1 failed with the following error message: The path is not of a legal form. For more information, see the about_Remote_Troubleshooting 
> Help topic.

**Comment by rpsqrd** [comment]
Closing as this issue is now 1 year old. Please file an issue (or even a pull request) against [PowerShell/PowerShell](https://github.com/powershell/powershell) if you wish to have this error message improved.
