### ISSUE TITLE
No documentation for RunAsVirtualAccountGroups setting

### ISSUE THREAD

**Issue by artisticcheese** [PowerShell/JEA#4]
No docs

**Comment by alexaymonier** [comment]
Looks like it's here
https://msdn.microsoft.com/powershell/reference/5.1/microsoft.powershell.core/New-PSSessionConfigurationFile 


-RunAsVirtualAccountGroups

Specifies the security groups to be associated with the virtual account when a session that uses the session configuration is run as a virtual account. If omitted, the virtual account belongs to Domain Admins on domain controllers and Administrators on all other computers.

Type: String[]
Parameter Sets: (All)
Aliases: 

Required: False
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False

**Comment by artisticcheese** [comment]
Yes, this can be closed now. It was not documented at the time of ticket being open.

**Comment by jmesa772** [comment]
I'm trying to use an endpoint on a Domain Controller but I'm getting access denied, this happens if I leave -RunAsVirtualAccountGroups with no value or even if I specify Domain Admins group. See that virutal account is not being added to domain admins group, any suggestions?
